### ISSUE TITLE
Milestone: The paucity of Amerine Menu Metadata

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-menu-data#4]
this [Google Sheet](https://docs.google.com/spreadsheets/d/1w5oUm8KXgTfyvLt77AlUF7ERAAWxE2yMMuGmDOZqDDA/edit?usp=sharing) includes the metadata that has currently been collected for the Amerine Wine Labels.  The folder level  is what was received from Act 4, presumably from UC Davis special collections.  It's incredibly short in the context I have, many menus with no metadata what-so-ever.

Act 4 then showed a crosswalk from the folder metadata to the individual files.  This is how we associate the images with the folders.

Later, more metadata was added to a small set of menus, and the final collated version includes all that information.  

We need to verify is this is the sum total of metadata we have available, and if not, we need to add the other metadata to this repository.

**Comment by EricNebeker** [comment]
I'll ask around to see if there is more metadata hiding anywhere. If not, I think we'll need to discuss practical ways to complete the metadata.
