### ISSUE TITLE
Image file updates / Archive? 

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-menu-data#5]
The Act 4 digitized DNGs came in the least processed format.  We have a process to crop and color fix the menus.  Now we have a question, are the original versions from Act 4 the archive version, or are they an intermediate component to the archive version? Should they be added to the DAMS? Should they be public? 

This is hampered by the fact that 1) The colors were modified, and 2) Some of the automated cropping did not work properly.

## Good Example DNG 2320 

Here's an example of a well done auto crop.

![Original](https://user-images.githubusercontent.com/344953/40739931-4dbbc744-63fc-11e8-940f-e0c8ef1b2ad0.png)

![Updated](https://user-images.githubusercontent.com/344953/40739822-0ab54de4-63fc-11e8-91ed-d89ce1caaf91.png)

## Bad Example DNG file 1178

This example shows where the background was too light and the image was not cropped correctly.

![Original](https://user-images.githubusercontent.com/344953/40739286-a4656c00-63fa-11e8-9b5e-746958a1331d.png)

![Updated](https://user-images.githubusercontent.com/344953/40739628-8d490440-63fb-11e8-83ca-758f1c9890ac.png)

**Comment by EricNebeker** [comment]
@qjhart Where can I find these image files? I don't see them at imgarc or bigsys/digtalcoll.

**Comment by qjhart** [comment]
@EricNebeker I haven't put them up anywhere yet.  I was going to add them to google drive, but I thought maybe it'd be better to just put them in an example dams.

**Comment by EricNebeker** [comment]
@qjhart Ok. I’ll grab a few to look at in the meantime.
